---

- name: Copy artifact.tar.gz to EC2
  copy:
    src: files/artifact.tar.gz
    dest: ~/
- name: "Extract Artifact"
  become: true
  shell: tar -xvzf ~/artifact.tar.gz
- name: "start server"
  become: true
  shell: |
    npm install
    pm2 stop default
    sudo pm2 start npm --start