version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: change directory
          command: ls
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: build projet
          command: npm run build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: change directory
          command: cd ../backend
      - run:
          name: install dependencies of backend
          command: npm install
      - run:
          name: build projet
          command: npm run build

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend