version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: build front-end project
          commands: |
            cd frontend
            npm install
            npm run build
            exit 1

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          name: build back-end project
          commands: |
            cd backend
            npm install
            npm run build
            exit 1

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend